development:
  xxxx: hogehoge
  xxxx: hogehoge
  xxxx: hogehoge
  xxxx: hogehoge
  xxxx: hogehoge
  aws_access_key_id: <%= ENV["AWS_ACCESS_EY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  secret_key_base: b2f21e3c38e80f6f772f9172e53134ebc3ee08b1014be158d129e7269290e647af439e4037063e30fcfd4180a4de28afb61882358f1a306f5acb4285a8ae7a52

test:
  secret_key_base: 2b791250a7fa8e59d032b4f132f328ef812992c76022dc72cc1b0394db41869baf836a8eb73daea2621945b583bc8b4da38fae9fc8c131b400f443368ee25887

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
